// <auto-generated />
using System;
using MainService.DAL.Context;
using MainService.DAL.Context.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MainService.DAL.Migrations
{
    [DbContext(typeof(PostgreDbContext))]
    [Migration("20251015100356_init-with-indexes")]
    partial class initwithindexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MainService.DAL.Features.Courses.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseLanguageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LearningLanguageId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("LearningLanguageId");

                    b.HasIndex("BaseLanguageId", "LearningLanguageId")
                        .IsUnique();

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7ff9cff2-4cf1-45db-aa70-855bb69e507d"),
                            BaseLanguageId = new Guid("8dc05007-6ed9-406a-9eeb-fbbf748283e2"),
                            LearningLanguageId = new Guid("8e5a2463-e8d1-427a-bd84-9386e073999f"),
                            Status = true
                        });
                });

            modelBuilder.Entity("MainService.DAL.Features.Courses.Models.UserCourse", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("UserCourses");
                });

            modelBuilder.Entity("MainService.DAL.Features.Languages.Models.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8dc05007-6ed9-406a-9eeb-fbbf748283e2"),
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("8e5a2463-e8d1-427a-bd84-9386e073999f"),
                            Name = "German"
                        },
                        new
                        {
                            Id = new Guid("419ce969-51ab-41c9-9d2f-ae0f007d3b2d"),
                            Name = "Russian"
                        },
                        new
                        {
                            Id = new Guid("5715abc0-de4e-4a5c-bd9c-4edcbade3e09"),
                            Name = "French"
                        });
                });

            modelBuilder.Entity("MainService.DAL.Features.Lessons.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderNum")
                        .HasColumnType("integer");

                    b.Property<string>("TestId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("Name");

                    b.HasIndex("TestId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("MainService.DAL.Features.Translations.Models.Translation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromWordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToWordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ToWordId");

                    b.HasIndex("FromWordId", "ToWordId", "CourseId")
                        .IsUnique();

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1b2c3d4-e5f6-4789-abc1-123456789001"),
                            CourseId = new Guid("7ff9cff2-4cf1-45db-aa70-855bb69e507d"),
                            FromWordId = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789001"),
                            ToWordId = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789006")
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-e5f6-4789-abc1-123456789002"),
                            CourseId = new Guid("7ff9cff2-4cf1-45db-aa70-855bb69e507d"),
                            FromWordId = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789002"),
                            ToWordId = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789007")
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-e5f6-4789-abc1-123456789003"),
                            CourseId = new Guid("7ff9cff2-4cf1-45db-aa70-855bb69e507d"),
                            FromWordId = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789003"),
                            ToWordId = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789008")
                        });
                });

            modelBuilder.Entity("MainService.DAL.Features.Users.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PasswordHash")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-1234567890ab"),
                            Email = "testuser@example.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEFakeHashedPassword1234567890",
                            Status = true,
                            Username = "testuser"
                        });
                });

            modelBuilder.Entity("MainService.DAL.Features.Users.Models.UserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MistakesMade")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Period")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StreakLength")
                        .HasColumnType("integer");

                    b.Property<int?>("TestsFinished")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WordsLearned")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("MainService.DAL.Features.Users.Models.UserTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderNum")
                        .HasColumnType("integer");

                    b.Property<string>("TestId")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserTests");
                });

            modelBuilder.Entity("MainService.DAL.Features.Words.Models.UserWord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "WordId");

                    b.HasIndex("WordId");

                    b.ToTable("UserWords");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-1234567890ab"),
                            WordId = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789001"),
                            AddedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-1234567890ab"),
                            WordId = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789002"),
                            AddedAt = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-1234567890ab"),
                            WordId = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789003"),
                            AddedAt = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-1234567890ab"),
                            WordId = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789006"),
                            AddedAt = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-1234567890ab"),
                            WordId = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789007"),
                            AddedAt = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MainService.DAL.Features.Words.Models.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("Text")
                        .IsUnique();

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789001"),
                            LanguageId = new Guid("8dc05007-6ed9-406a-9eeb-fbbf748283e2"),
                            Text = "Hello"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789002"),
                            LanguageId = new Guid("8dc05007-6ed9-406a-9eeb-fbbf748283e2"),
                            Text = "Goodbye"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789003"),
                            LanguageId = new Guid("8dc05007-6ed9-406a-9eeb-fbbf748283e2"),
                            Text = "Thank you"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789004"),
                            LanguageId = new Guid("8dc05007-6ed9-406a-9eeb-fbbf748283e2"),
                            Text = "Please"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789005"),
                            LanguageId = new Guid("8dc05007-6ed9-406a-9eeb-fbbf748283e2"),
                            Text = "Water"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789006"),
                            LanguageId = new Guid("8e5a2463-e8d1-427a-bd84-9386e073999f"),
                            Text = "Hallo"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789007"),
                            LanguageId = new Guid("8e5a2463-e8d1-427a-bd84-9386e073999f"),
                            Text = "Auf Wiedersehen"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789008"),
                            LanguageId = new Guid("8e5a2463-e8d1-427a-bd84-9386e073999f"),
                            Text = "Danke"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789009"),
                            LanguageId = new Guid("8e5a2463-e8d1-427a-bd84-9386e073999f"),
                            Text = "Bitte"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4789-abc1-123456789010"),
                            LanguageId = new Guid("8e5a2463-e8d1-427a-bd84-9386e073999f"),
                            Text = "Wasser"
                        });
                });

            modelBuilder.Entity("MainService.DAL.Features.Courses.Models.Course", b =>
                {
                    b.HasOne("MainService.DAL.Features.Languages.Models.Language", "BaseLanguage")
                        .WithMany()
                        .HasForeignKey("BaseLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MainService.DAL.Features.Languages.Models.Language", "LearningLanguage")
                        .WithMany()
                        .HasForeignKey("LearningLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseLanguage");

                    b.Navigation("LearningLanguage");
                });

            modelBuilder.Entity("MainService.DAL.Features.Courses.Models.UserCourse", b =>
                {
                    b.HasOne("MainService.DAL.Features.Courses.Models.Course", "Course")
                        .WithMany("UserCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.DAL.Features.Users.Models.User", "User")
                        .WithMany("UserCourses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MainService.DAL.Features.Lessons.Lesson", b =>
                {
                    b.HasOne("MainService.DAL.Features.Courses.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("MainService.DAL.Features.Translations.Models.Translation", b =>
                {
                    b.HasOne("MainService.DAL.Features.Courses.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.HasOne("MainService.DAL.Features.Words.Models.Word", "FromWord")
                        .WithMany()
                        .HasForeignKey("FromWordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MainService.DAL.Features.Words.Models.Word", "ToWord")
                        .WithMany()
                        .HasForeignKey("ToWordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("FromWord");

                    b.Navigation("ToWord");
                });

            modelBuilder.Entity("MainService.DAL.Features.Users.Models.UserInfo", b =>
                {
                    b.HasOne("MainService.DAL.Features.Users.Models.User", "User")
                        .WithOne("Userinfo")
                        .HasForeignKey("MainService.DAL.Features.Users.Models.UserInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MainService.DAL.Features.Users.Models.UserTest", b =>
                {
                    b.HasOne("MainService.DAL.Features.Users.Models.User", "User")
                        .WithMany("UserTests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MainService.DAL.Features.Words.Models.UserWord", b =>
                {
                    b.HasOne("MainService.DAL.Features.Users.Models.User", "User")
                        .WithMany("UserWords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainService.DAL.Features.Words.Models.Word", "Word")
                        .WithMany("UserWords")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("MainService.DAL.Features.Words.Models.Word", b =>
                {
                    b.HasOne("MainService.DAL.Features.Languages.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("MainService.DAL.Features.Courses.Models.Course", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("UserCourses");
                });

            modelBuilder.Entity("MainService.DAL.Features.Users.Models.User", b =>
                {
                    b.Navigation("UserCourses");

                    b.Navigation("UserTests");

                    b.Navigation("UserWords");

                    b.Navigation("Userinfo")
                        .IsRequired();
                });

            modelBuilder.Entity("MainService.DAL.Features.Words.Models.Word", b =>
                {
                    b.Navigation("UserWords");
                });
#pragma warning restore 612, 618
        }
    }
}
