name: Langtice CI/CD

on: 
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      
      - name: Restore dependencies
        run: dotnet restore

      
      - name: Clean the solution
        run: dotnet clean

      
      - name: Build the solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test MainService/MainService.Tests/MainService.Tests.csproj 
          --no-build --configuration Release \
          --logger "trx;LogFileName=test-results.trx" \
          --results-directory TestResults

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: 'Test Results'
          path: 'TestResults/*.trx'
          reporter: dotnet-trx
